baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "SPP 608"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Viviana Chiu Sik Wu"
  bio = ""
  job = "Assistant Professor"
  location = "The University of Massachusetts Amherst"
  gravatarEmail = "vivianachius@umass.edu"
  # Your profile picture
#  picture = ""
  twitter = "vivianacswu"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "schedule"
  name = "Schedule"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://rstudio.cloud"
[[menu.main]]
  weight = 5
  identifier = "moodle"
  name = "GitHub"
  pre = "<i class=\"material-icons\">moodle_logo</i>"
  url = "https://moodle.umass.edu/"
[[menu.main]]
  weight = 6
  identifier = "gradescope"
  name = "Gradescope"
  pre = "<i class=\"material-icons\">gradescope_logo</i>"
  url = "https://www.gradescope.com/"


[[menu.footer]]
  weight = 1
  identifier = "UMass"
  name = "UMass Public Policy"
  pre = "<i class=\"material-icons\">spp_logo</i>"
  url = "https://www.umass.edu/spp/"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/"
[[menu.footer]]



[params]
  dateFormat = "January 2, 2006"
  background = "<i class=\"material-icons\">background</i>"
  favicon = "img/Class_logo"
